# ==============================================================================
#         ARQUIVO DE CONFIGURAÇÃO DE PARÂMETROS DA SIMULAÇÃO
# ==============================================================================
# Parâmetros são externalizados para facilitar a manutenção sem alterar o código.

# Executável do SUMO a ser usado ('sumo' para linha de comando, 'sumo-gui' para visual).
sumo_executable: "sumo-gui"

# Porta de conexão para o TraCI, evitando conflitos com outras aplicações.
traci_port: 8813

# Mapeamento de nomes de cenários para seus respectivos arquivos de configuração.
scenarios:
  osm: "scenarios/from_osm/osm.sumocfg"
  api: "scenarios/from_api/api.sumocfg"

# Centraliza todos os caminhos de saída para manter o projeto organizado.
output_paths:
  logs: "logs"
  dashboards: "output"
  # Nome do arquivo de relatório gerencial com as médias.
  report_file: "simulation_report.log"
  # Nome do arquivo de dados estruturados para consumo por outras ferramentas.
  consolidated_data: "consolidated_data.json"

# Configurações para o controlador de tráfego adaptativo.
# Exemplo de como estruturar parâmetros complexos.
traffic_lights:
  - id: "J1" # ID do semáforo no arquivo .net.xml
    phases:
      # A estrutura de fases permite configurar o comportamento de cada semáforo.
      - duration: 30
        min_duration: 15
        max_duration: 45
        state: "GGrrGGrr"
      - duration: 4
        state: "yyrryyrr"
      - duration: 30
        min_duration: 15
        max_duration: 45
        state: "rrGGrrGG"
      - duration: 4
        state: "rryyrryy"